def init() -> None: ...
def close() -> None: ...

class PyPhase:
   def datalen(self) -> int: ... 
   def sampling_frequency(self) -> float: ...
   def labels(self) -> List[str]: ...

   def raw_data(self, channel: str, start: Optional[int] = None, end: Optional[int] = None) -> List[float]: ...
   def set_raw_data(self, channel: str, data: List[float], start: Optional[int] = None) -> bool: ...

   def n_digitals(self) -> int: ...
   def digital(self, index: int, start: Optional[int], end: Optional[int]) -> List[float]: ...
   def set_digital(self, index: int, data: List[float], start: Optional[int]) -> bool: ...

   def n_events(self) -> int: ...
   def events(self, index: int) -> List[int]: ...

   def peak_train(self, channel: str, start: Optional[int], end: Optional[int]) -> Tuple[List[int], List[float]]: ...
   def set_peak_train(self, channel: str, data: Tuple[List[int], List[float]], start: Optional[int], end: Optional[int]) -> bool: ...
